### ISSUE TITLE
Design global form actions component 

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-carts-seds#113]
The bottom of each page in the report will have the same actions displayed consistently across the application. The actions a user can take in each section are:

- [x] Go to the previous page
- [x] Go to the next page
- [x] Let a user save or understand that the document has been auto-saved
- [x] Let a user share the document in its current state with other members of their organization to fill out or view.
  - We were calling "export" "share" "download and print" but due to technical constraints is more accurately and realistically, "This will bring you to a page where you can print or save as PDF and share with others." This doesn't quite fit in a button or roll of the tongue so this section still needs work.

<img width="839" alt="Screen Shot 2020-06-24 at 7 07 25 PM" src="https://user-images.githubusercontent.com/23194720/85636250-f6f1cc00-b64d-11ea-8be7-001e754f3eaa.png">

### Dependency and blockers:
- [x] Define the process and technical limitations of the "export" functionality
- [x] Design a non-editable view/review view.
- [x] Design a `print.css` view

Note: 
- Very strong candidate for next round of usability testing

**Comment by erinzstrenio** [comment]
@austinhernandez Looks great!

Is there a "save" button too or just the auto-save function? Curious since you noted the action to "Let a user save..."

**Comment by austinhernandez** [comment]
@erinzstrenio document will auto-save, letting a user save was a fallback in case this was not technically feasible.

**Comment by austinhernandez** [comment]
Notes from co-work: 6/25

- The actions aside from go to the previous page, go to the next page will be to generate a temporary URL to share (`share this page`) and open the print preview dialog box so they can print or save as a PDF (`print`). 
  - names subject to change. 

- `Share this page` Will generate a temporary URL that a user can copy and send (via email, chatter, gchat... etc.) to a colleague to fill out. It will share only that page/subsection with the data from the previous year available. only the to share and 
- Print: Will open the print preview page [essentially like pressing ctrl/cmd P]


- [ ] This ticket will just be the global footer design with auto-save, previous, next, print, and share this page buttons.
- Design review view is in a new ticket #118 
- Design the `print.css` view of the subsections is a new ticket #119

**Comment by austinhernandez** [comment]
right?
<img width="816" alt="right" src="https://user-images.githubusercontent.com/23194720/85818362-7d85d680-b73e-11ea-8776-6cafae1df51b.png">

outside?
<img width="822" alt="outside" src="https://user-images.githubusercontent.com/23194720/85818364-7e1e6d00-b73e-11ea-96b0-6f52e7cc1dd6.png">

inside?
<img width="798" alt="inside" src="https://user-images.githubusercontent.com/23194720/85818366-7eb70380-b73e-11ea-8496-36f54555801d.png">

**Comment by cannandev** [comment]
@austinhernandez I like **Right** ➡️  🙋🏾‍♀️
