### ISSUE TITLE
Change basic information page

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-carts-seds#117]
Hello! Here are the design changes for https://cartsdemo.cms.gov/basic-info

- [x] Remove `Welcome!` text
- [x] Add tabs to this page to make it consistent with other tabbed pages like 2b and 3c
- [x] The 2 tabs should read `Basic information` and `FY2019 answers`
- [x] Remove `Let’s start with your basic information.`
- [x] Keep questions `1. State or territory name:` , `2. Program type:` , and `3. CHIP program name(s):` but they should be uneditable / use the disabled field style. These should pre-populate from data we already know about the user!
- [x] Add a text link below question 3 saying `This is incorrect` (the wording on this might change slightly) which will allow a user to contact helpdesk `mailto:CARTSHELP@cms.hhs.gov` 
- [x] Questions 4-8 will have the same functionality as 3c where a user can copy over their answers for each field from the previous year.
- [x] Tab `FY2019 answers` will have answers from the previous year 
- [x] Address field will use a [text area instead of field](https://uxmovement.com/forms/why-you-should-use-a-text-area-for-address-form-fields/)
- [x] Change label to `7. Full mailing address`
- [x] Field should have appropriate inline validation for email (@, no random characters etc) 
- [x] Field should have appropriate inline validation for phone number (10 digits, no random punctuation, allow for - and . as number divider, etc. )
- [x] User controls section (prev, next, saved, etc.) coming on another ticket (in progress at [#113 ]

![2020-06-25-14-01-cartsdemo cms gov](https://user-images.githubusercontent.com/23194720/85797278-51039780-b709-11ea-9d11-ebfc5c71f368.png)

**Comment by jgillis1** [comment]
Set New York as a Combo state for Demo purposes.

**Comment by jgillis1** [comment]
@austinhernandez Validation of format for email and phone number will occur on page save. Is that acceptable?
