### ISSUE TITLE
Prototype: Update 2B to reflect latest legal

### ISSUE THREAD

**Issue by cannandev** [18F/cms-carts-seds#125]
Related to #77.

[2B document](https://docs.google.com/document/d/1I-pnJCrsceEaIoFjHMQOqApQBBdyPj2e7Olqc0nK_eI/edit?usp=sharing): 
<link to prototype>
Please update the following:

- [x] Clicking discontinued shows rest of form; but they can still add additional objectives/goals to fit their state plans.
- [x] All questions are now numbered.
- [x] First objective is always hardcoded to “reduce the number of uninsured children”.
- [x] Add blue left-border on fieldset (see https://design.cms.gov/components/choice) .
- [x] Follow heading styles for each question in [invision](https://gsa.invisionapp.com/share/6CWTUB9R3XN#/screens/417945156).

**Comment by jgillis1** [comment]
Few items still pending a push.

**Comment by alewoo28** [comment]
I didnt mean to close this, sorry about that!
I have some questions about the last 2 bullets. 
@cannandev 
What areas do you want the blue left border on?
Which headings are not in line with the invision prototype?

**Comment by jgillis1** [comment]
Blue left border on conditionals might be corrected with new release of CMS Style Sheet. Still waiting for release 3.7.1 as of 7/2/2020 @ 10:50 AM Eastern.

**Comment by cannandev** [comment]
Thanks @alewoo28 
Under https://design.cms.gov/components/choice/ (way at the bottom of the doc) There's a different property `checkedChildren` for **radios with children**. That should display the blue border.

![image](https://user-images.githubusercontent.com/381122/86386573-f1a10c80-bc5f-11ea-9a06-e82f2b62ca79.png)

lmk if that works

**Comment by andrewadcock** [comment]
Unfortunately, that is exactly what we are waiting for in the next release (3.7.1).

**Comment by jgillis1** [comment]
Review of 2B scheduled with @cannandev and @alewoo28 for 7/8/2020.

**Comment by jgillis1** [comment]
I am going to close this ticket as all items but the blue left border on fieldset have been completed. Since completing this item requires a new version of the CMS Style Sheet to be released, we cannot complete this item at this time. I will open a separate ticket specifically for this and any code refactoring that is required once the release is available and we can work through this at that time.
