### ISSUE TITLE
Build HTML based non-interactive view AKA review view

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-carts-seds#135]
The non-interactive review view is only accessible from the homepage by clicking the "view button" or the document a user sees upon "certifying". This view is only available in entire form view, not section by section. It serves as an un-editable form that reduces the length of the document for records and review:

Accessible through these links on the homepage:
<img width="364" alt="Screen Shot 2020-06-25 at 8 37 37 PM" src="https://user-images.githubusercontent.com/23194720/85808804-f75c9680-b723-11ea-9236-e08aa23eb2f9.png">

Non-interactive view v1 (annotated):
![Non-interactive view AKA review view](https://user-images.githubusercontent.com/23194720/86294647-fa8fd080-bbc2-11ea-82ae-3890d4000a07.png)

**AC**: Many of these tasks are noted in the annotated mockup:
- [x] This view opens in a new tab (or window if tab is unavailable) 
- [x] Text does not extend to the full page to allow for easy scanability and writing in the margins
- [x] Removed interactive elements such as input fields, text areas, buttons, links, etc.
- [x] Removed header and footer
- [x] Only display selected radio button or checkbox 
- [x] Use minimal color to optimize printing
- [x] Change conditional radio button left border to gray
- [x] Change selected radio button or checkbox to outline with black checkmark
- [x] If there is no selection on a radio button or checkbox, please display them all
- [x] If there is a conditional question that is unanswered, show hidden questions. 
- [x] Instead of input fields and text areas, there is bottom padding (of ~70px) beneath a question so a user can tell a question is empty or unanswered 
- [x] Keep the helper text if applicable on unanswered questions

**Comment by cannandev** [comment]
@alewoo28 @tadhg-ohiggins  routes for this view should be /reports/`ss`/`yyyy`
where `ss` is state

**Comment by erinzstrenio** [comment]
As we discussed in standup today: 
Show conditional questions in the non-interactive view if state user hasn't answered the parent question yet. 

For example:
Show part A of Q1 if they haven't answered Q1 yet. 

<img width="568" alt="Screen Shot 2020-07-22 at 12 52 33 PM" src="https://user-images.githubusercontent.com/46569779/88210733-4231d700-cc1a-11ea-8b59-b027b0b9722c.png">
