### ISSUE TITLE
Postgres Database Audit Logs

### ISSUE THREAD

**Issue by ayushi-roy** [18F/cms-carts-seds#145]
As a CMS / IT Security user of CARTS, I need to be able to create audit logs and then push them to the appropriate CMS repository within the extension of the CI/CD process. (Application to Cloudwatch)

AC:

- [x] Database logs are created (current recommendation from @tadhg-ohiggins: try installing the `django-reversion` module)
- [x] Database backups are 3 weeks plus daily snapshots
- [ ] Any new modules used for audit logging are added to deployment scripts (e.g. `requirements.txt`)
- [x] Console logs are sent to splunk

(Related to #279?)

**Comment by jgillis1** [comment]
@tadhg-ohiggins 
After discussion with Doug and looking at AWS, logs are currently being outputted to CloudWatch. We need to review and determine if the level of logging that is occurring is acceptable.

At some point it may be necessary to change the logging path.

**Comment by jgillis1** [comment]
9/15/2020 Update: Per Berry, this is possible to do within the postgres DB. That team will not start work on this till next week (9/21) and will take about a week to complete and deploy as an automated configuration.

**Comment by jgillis1** [comment]
This was completed with JIRA Issue [OY2-252](https://qmacbis.atlassian.net/browse/OY2-252)
