### ISSUE TITLE
Secure approval to receive SEDS data

### ISSUE THREAD

**Issue by ayushi-roy** [18F/cms-carts-seds#148]
We need access to Line 7 from SEDS Q4 report - required to be displayed in section 2a CARTS.

- [x] @jgillis1 to ascertain whether or not we can bring over all the past SEDS data in the same manner as the past CARTS data.

- More tasks after we have the info from the first item.

AC:
1. CMS approval
2. Leidos approval

**Comment by cannandev** [comment]
CL has solution proposal to submit to CMS. If submitted and approved will make getting SEDS data easy.

**Comment by jgillis1** [comment]
Relates to #189

**Comment by tadhg-ohiggins** [comment]
Will be finished if #190 is completed.

**Comment by TaraWilliamsPGH** [comment]
SEDS data connection has been approved by CMS; still waiting on the connection from Leidos.

**Comment by jgillis1** [comment]
Leidos confirmed they opened the port ad of 8/10/2020.

CL Data Team is testing the connection.
