### ISSUE TITLE
ATO Execution

### ISSUE THREAD

**Issue by ayushi-roy** [18F/cms-carts-seds#154]
AC:

- [ ] Disaster recovery documentation is created

- [ ] Roll-back plans in place

- [ ] Smoke testing

- [ ] All required security documentation completed (must confirm with Eric to mark this item complete)

- [ ] ATO is issued

**Comment by ayushi-roy** [comment]
Does the notion of a "pilot" exist? Can we provide early access?

**Comment by cannandev** [comment]
Eric Hill. Will need documentation from Doug and Tadhg.

**Comment by TaraWilliamsPGH** [comment]
Notion of pilot does exist, but we cannot do it.

**Comment by ayushi-roy** [comment]
Related #43

**Comment by TaraWilliamsPGH** [comment]
Closed - we only need to include pen test documentation. Pen test ticket #387

**Comment by cjhskippy** [comment]
Removing milestone, since this was removed from scope
