### ISSUE TITLE
Follow up on PRA

### ISSUE THREAD

**Issue by ayushi-roy** [18F/cms-carts-seds#156]

**Comment by TaraWilliamsPGH** [comment]
@StephanieCoppel please let us know what the status is on this item.

**Comment by StephanieCoppel** [comment]
it is undergoing review, DSCP has confirmed it is actively going through the review process. thats as much insight as we can get at this point unfortunately

**Comment by cjhskippy** [comment]
Per @StephanieCoppel : the updated template has PRA approval, big hurdle cleared!
