### ISSUE TITLE
Create Date Range component to capture dates

### ISSUE THREAD

**Issue by cannandev** [18F/cms-carts-seds#158]
Let's use four fields (two `<DateField>` components) to capture dates throughout the application. We already have this in section 2B. Let's make this into a reusable component.

For example, Section 2A - question 3b. Instead of a textfield, use the date range component. As a child element, It should be styled as a conditional  (blue border-left)

![Screen Shot 2020-07-02 at 2 03 32 PM](https://user-images.githubusercontent.com/381122/86394707-fc15d300-bc6c-11ea-93a0-dd829601ced6.png)

**Comment by jgillis1** [comment]
- [ ] Ensure only a valid 1 or 2 digit Month is entered
- [ ] Ensure only a valid 4 digit Year is entered
- [ ] Ensure the Month & Year combination are valid
- [ ] Ensure the Start Date and End Date are in chronological order

**Comment by jgillis1** [comment]
@cannandev could you please review, approve and close at your convenience?

**Comment by jgillis1** [comment]
@cannandev updates have been made and pushed to `master`. Please review at your convenience.

**Comment by cannandev** [comment]
Looks good!
