### ISSUE TITLE
Add blue left-border on fieldset after CMS SS Update

### ISSUE THREAD

**Issue by jgillis1** [18F/cms-carts-seds#167]
After a new release of the CMS Style Sheet is available:

- [x] Add blue left-border on fieldset (see https://design.cms.gov/components/choice) for child items.
- [x] Refactor code throughout as needed

- [x] Section 1
- [x] Section 2A
- [x] Section 3A
- [x] Section 3C

**Comment by jgillis1** [comment]
CMS Design System v3.7.2 is now available
[](https://github.com/CMSgov/design-system/releases/tag/v3.7.2)

**Comment by andrewadcock** [comment]
The design system has been updated, however, the fix does NOT appear to be working. An issue has been opened with the CMS design system team (https://github.com/CMSgov/design-system/issues/735) and we are working through it.

**Comment by jgillis1** [comment]
Section 1 pushed in merge #223
