### ISSUE TITLE
Finish revising content in CARTS section 1

### ISSUE THREAD

**Issue by erinzstrenio** [18F/cms-carts-seds#18]
section 1 draft: https://docs.google.com/document/d/1P6mFgRd8dsm1YIiHo1pDcIzWA119k5tIKNGTbbC9WVQ/edit

**Comment by erinzstrenio** [comment]
- [x] Add draft of section 1 to [content doc](https://docs.google.com/document/d/1gzsMnsuBe9jf67O4z8djmxGPSGToujBFaMyYzx9IlyA/edit#heading=h.e50zmju70zdz) 
- [ ] Waiting on examples from Cassie and Tess

**Comment by cannandev** [comment]
@erinzstrenio I think this is ready to close, yes?

**Comment by erinzstrenio** [comment]
@cannandev almost!! just added a to-do item about the first checkbox and whether we need to keep it or not

**Comment by cannandev** [comment]
Created #90 to start Section 1.
