### ISSUE TITLE
SQL Server to Postgres Data Translation

### ISSUE THREAD

**Issue by jgillis1** [18F/cms-carts-seds#190]
Work with CollabraLink Data Team to determine feasibility of using AWS DMS to do a data translation of CARTS/SEDS SQL Server data to Postgres

Set up sample data migration and data translation from SQL Server to Postgres

AC:

1. Legacy CARTS/SEDS tables available in Postgres in new app

**Comment by jgillis1** [comment]
7/23/2020 Update:
- We have created the SQL Server DB and Postgres DB on AWS as source and target respectively. Created CARTS and SEDS schema on both. Created tables from extract. We are working on loading the extract data to the Source DB.
- Nathan has submitted a firewall request to Leidos to open up connectivity to our account for a dev database (SNOW Ticket: CHG0065263)

**Comment by jgillis1** [comment]
- Initial translation is complete
- ACME Dev to verify that content looks correct
- Leidos should open firewalls by week of 8/10

**Comment by TaraWilliamsPGH** [comment]
The point value for this ticket needs to be changed in order to roll over to sprint Funfetti. @jgillis1 can you please create the new ticket and link it to this ticket. Please close this ticket once new ticket is created.

**Comment by jgillis1** [comment]
Closing this ticket. Continued activities are in #277
