### ISSUE TITLE
Stand-up Postgres Database for New Data

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [18F/cms-carts-seds#199]
Complete database build plus any associated design documents.

- [x] Create local postgres DB instance (this can be a shell DB with a simple test table)

- [x] Create Django models

- [ ] Deploy to AWS
- [ ] Create connection to AWS DB instance - verify the simple test table can be accessed and read
- [x] Update README with necessary connection information
- [ ] `cartsdemo.cms.gov` can read from deployed Django/Postgres API/DB.

It would be ideal if this could be completed within the first week of the Sprint and remaining Sections with content can be built out in the second week of the Sprint.

**Comment by jgillis1** [comment]
I believe ultimately we want to all dev against the same DB environment and not a local DB so I think we should move forward with creating the DB in AWS and connecting to that (it may require the developer to be on the Cloud VPN to access).
