### ISSUE TITLE
Design of Section 4

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [18F/cms-carts-seds#213]

**Comment by TaraWilliamsPGH** [comment]
AC:

- [ ] Section content is created

- [ ] Section content is approved (as needed)

**Comment by erinzstrenio** [comment]
google doc for section 4: https://docs.google.com/document/d/1N3wgjF4VwMd9HXG7F8xYS13nswctSC03c41HkvGMOus/edit?usp=sharing
