### ISSUE TITLE
Design of Section 5

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [18F/cms-carts-seds#214]

**Comment by TaraWilliamsPGH** [comment]
AC:

- [ ] Section content is created

- [ ] Section content is approved (as needed)

**Comment by erinzstrenio** [comment]
Moved it to CL folder: https://docs.google.com/document/d/1R6e3ZWL-Xc1TG2GBW4XFe4peCFCX4uyDYMbH9fX3CPM/edit?usp=sharing
