### ISSUE TITLE
Design of Certify and Submit Page

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [18F/cms-carts-seds#216]
AC:

- [x] Section content is drafted

- [x]  Review with @tadhg-ohiggins 

- [x]  Section content is revised/approved (as needed)

- [x]  Review with @austinhernandez

- [ ] Design of section by @austinhernandez

**Comment by TaraWilliamsPGH** [comment]
AC:

- [ ] Section content is created

- [ ] Section content is approved (as needed)

**Comment by jgillis1** [comment]
Here is the existing Certify & Submit page. Upon certification, the status of the report changes to "Certified".

![image](https://user-images.githubusercontent.com/36236589/90182992-cf330080-dd80-11ea-91c6-af6356b83029.png)

**Comment by erinzstrenio** [comment]
Google doc for this page: https://docs.google.com/document/d/1cCUtj1fiHd9HxNVknyHwKLiorT428NQ5G5AMLMDr8qA/edit?usp=sharing

**Comment by austinhernandez** [comment]
designed, and updated #385  dev ticket

![CARTS review and submit2](https://user-images.githubusercontent.com/23194720/92525402-c56eb280-f1f1-11ea-943d-c9d3844382fa.png)

![CARTS review and submit1](https://user-images.githubusercontent.com/23194720/92525401-c56eb280-f1f1-11ea-8212-eae8a9289fd7.png)
