### ISSUE TITLE
Update section 5 of the CARTS System Design Document

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/cms-carts-seds#227]
Use existing CARTS SDD as template, but cut large swathes that are no longer relevant  (current doc references a T1 line!). We should be inheriting a lot of controls from AWS, and hopefully also from CMS EIDM.

**Comment by tadhg-ohiggins** [comment]
Sent to Eric via email for feedback. I'll update the issue and include a link to this in Google Drive when it looks like this will be close to the final version.

**Comment by TaraWilliamsPGH** [comment]
Will reopen a new ticket if Eric requires additional information.
