### ISSUE TITLE
Rebuild Existing Static Sections Using Dynamic Format

### ISSUE THREAD

**Issue by jgillis1** [18F/cms-carts-seds#230]
All Sections that have been built out for the Prototype were built out in a static manner with only the answers being expected to be read from the backend.

The backend will provide answers AND questions as well as question type and expected response information. These sections will need to be re-written to take question information from the backend.

- [x] Basic Information @jgillis1 
- [x] Section 1 @andrewadcock 
- [x] Section 3A @andrewadcock

**Comment by jgillis1** [comment]
For Section 2A, be sure to reference #250

**Comment by jgillis1** [comment]
@tadhg-ohiggins 
Questions on Basic Info (Section 0)

1. State or Territory Name is set to text_long, should it be text_short so it is not multi-line?

1. Is there a property to know if the field should have the "copy from last year" button/option?

**Comment by tadhg-ohiggins** [comment]
1. I'll change that to `text_short`.
2. Display from last year is `context_data.display_prior_year_data` and is in the schema but not populated yet; I'll add `context_data.enable_copying_prior_year_data` to the schema today. (Both are booleans.)

**Comment by jgillis1** [comment]
@tadhg-ohiggins 
Some additional changes needed for Basic Info/Section 0

- [ ] subsection 2020-00-a needs a helpdesk or footer attribute that comes as the last attribute after all the questions: "If any of the above information is incorrect, contact CARTS Help Desk." so a link to the Help Desk email an be added

- [ ] id 2020-00-a-02-04 needs a hint "Include city, state and zip code"

![image](https://user-images.githubusercontent.com/36236589/89789040-13f33900-daee-11ea-9cc8-9291fe305875.png)

**Comment by jgillis1** [comment]
Creating a new ticket for 2B on its own.
