### ISSUE TITLE
Flat JSON for Sections 1 & 3A

### ISSUE THREAD

**Issue by jgillis1** [18F/cms-carts-seds#240]
DUE BY COB 7/27/2020

A flat JSON file will be completed for the following Sections and uploaded into GitHub repository for frontend development use:

- [x] Section 1
- [x] Section 3A
- [x] Documentation that includes conditional logic configuration schema.

@tadhg-ohiggins if these are the incorrect Sections that you believe you will complete by the end of the day today, please edit accordingly.

Linked to: #144

**Comment by tadhg-ohiggins** [comment]
At some point I mixed up 3A and 2A; 3A is one of the two I covered in my initial commit, and 2A is what Tim is looking at right now. I changed the descriptions here and in #241 to reflect the correct sections.

**Comment by tadhg-ohiggins** [comment]
These are present here https://github.com/18F/cms-carts-seds/tree/master/docs/section-schemas
