### ISSUE TITLE
Flat JSON File for All Remaining Sections with Content

### ISSUE THREAD

**Issue by jgillis1** [18F/cms-carts-seds#241]
DUE BY END OF ENTENMANN'S

A flat JSON file will be completed for the remaining Sections which content has been completed for and uploaded into GitHub repository for frontend development use:

- [x] JSON Schema definition to validate against.
- [x] Basic Information
- [x] Section 2B
- [ ] Section 2A @TGriesemer 
- [x] Section 3D

- [ ] Section 3 E

- [ ] Section 3F

@tadhg-ohiggins if these are the incorrect Sections that you believe you will complete by the end of the day today, please edit accordingly.

Linked to: #144

**Comment by TaraWilliamsPGH** [comment]
New ticket was created to roll over to Funfetti for item for sectiono 2A.

3E & F do not yet have completed content and therefore a JSON file is not needed at this time.
