### ISSUE TITLE
Create a new limited API endpoint

### ISSUE THREAD

**Issue by jgillis1** [18F/cms-carts-seds#25]
Add an endpoint to the API which pulls historical CARTS data that:

- [x] Includes information from Sections 2B and 4 only
- [x] Provides a more friendly way to identify the Question being answered

**Comment by andrewadcock** [comment]
- Ability to filter questionanswer endpoint by section (total filters: state, year, section)
    - section options 2b, 4, all (all displays both 2b and 4)
- Display additional question information including question text, start year, end year, etc

**Comment by jgillis1** [comment]
Completed in CollabraLink repo. Still needs to be migrated to this repo.
