### ISSUE TITLE
Refactor the Range Input component

### ISSUE THREAD

**Issue by cannandev** [18F/cms-carts-seds#250]
We want to make the range component used in Section 1 more flexible for other sections (e.g. 3E). Build a `<Range>` component to replace the `<FPL>`. 

Acceptance criteria:

- [ ] Display only 2 inputs (instead of 4) with generic labels: "Starts at" and "Ends at"
- [ ] Make `title`, `mask` and `numeric` all props. Wherever `<Range>` is used in the app, it should accept these prop values. 
**title** is the h3 heading of the component 
**mask** can be either `currency` or `percentage`. Use this value to show the % sign.
**numeric** is a boolean. Per the CMS docs, if it is passed to Textfield, it will set the inputmode, type and pattern of the Textfield.
- [ ] Remove the hardcoded inputmode, type and pattern
- [ ] Replace references in code from FPL to Range. 

Examples:

```
        <Range 
          title="Average Monthly Contribution" 
          mask="currency" 
          numeric
        />,
```
would look like 
![image](https://user-images.githubusercontent.com/381122/88743189-0a42fc00-d112-11ea-8f4a-d3475491afec.png)

Section 1 Q3 should have two components that look like this: 

![image](https://user-images.githubusercontent.com/381122/88742940-7bce7a80-d111-11ea-8b34-b8654c1be6f4.png)

**Comment by TaraWilliamsPGH** [comment]
Points will not be added to this ticket because the points have already been accounted for as it pertains to the build out of each of the sections.

**Comment by jgillis1** [comment]
PR #378
