### ISSUE TITLE
Postgres DB Build Out for Section JSON Structure

### ISSUE THREAD

**Issue by jgillis1** [18F/cms-carts-seds#253]
Build out postgres DB using JSON Structure
~Section 1~
~Section 3A~

It would be ideal if this could be completed within the first week of the Sprint and remaining Sections with content can be built out in the second week of the Sprint.

**Comment by lauraGgit** [comment]
*Tasks* 
- [ ] Create auth flow for client to hook into backend
- [ ] Create generic endpoint for baseline endpoint
- [ ]  section structure in json schema
