### ISSUE TITLE
Interaction tip from eAPD for auto-save

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-carts-seds#256]
All of the users from the most recent round of usability testing had difficulty finding and understanding the save interaction. The disabled text link color contrast is too low, and there is a mistrust from previous versions that work is saved. 

I suggest using the same code from eAPD's save button. During their usability testing, they found that users noticed the autosave functionality when there was an animation duration of 700ms between save and auto save buttons.

**Comment by cjhskippy** [comment]
Was no longer needed given the save behavior implemented so far.
