### ISSUE TITLE
Populated JSON data for component validation

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/cms-carts-seds#259]
Once the JSON document structure is ready, we'll need to test components/presentation of it with answers, thus requiring filled-out reports.

This should mean having data for three states:

- Alaska (Medicaid expansion CHIP).
- Arizona (Separate CHIP).
- Massachusetts (combination, and also one of the states with a premium assistance program).

Acceptance criteria:

- [ ] Populated JSON documents using 2019 data for Alaska.
- [ ] Populated JSON documents using 2019 data for Arizona.
- [ ] Populated JSON documents using 2019 data for Massachusetts.

Sections within these will only be possible to complete as they're completed in content/JSON schema design.

**Comment by cannandev** [comment]
Prefill 2B objectives with:

- Reducing the number of uninsured children
- Increasing access to care
- Increasing use of preventative care

**Comment by TaraWilliamsPGH** [comment]
If we have the historical data API, then we can build out the non-interactive view against that rather than using dummy data.
