### ISSUE TITLE
Static HTML generator reference implementation for non-interactive view

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/cms-carts-seds#261]
Make a generator that takes the JSON files and provides a basic HTML single-file output based on the data in them, in order to:
- Make the JSON data structure more comprehensible.
- Discover implementation wrinkles further in advance.
- Make it easier and faster to see the effects of content design decisions.
- Provide a reference point for implementation of both interactive and non-interactive views.
- Help in user testing by providing the link-id-for-every-question in a usable form.

Build it using a templating language (likely Mako) and use a component-based approach.

Acceptance criteria:

- [ ] Produces HTML output
    - [ ] … from JSON files that have no entries.
    - [ ] … from JSON files for 2019 Alaska data.
    - [ ] … from JSON files for 2019 Arizona data.
    - [ ] … from JSON files for 2019 Massachusetts data.
- [ ] Displays relevant sections according to basic conditional logic.
- [ ] Displays relevant sections according to the various pieces of more complex conditional logic scattered throughout the entire form.
- [ ] Has a component for every relevant component in the JSON schema.

**Comment by TaraWilliamsPGH** [comment]
If we have the historical data API, then we can build out the non-interactive view against that rather than using dummy data.

**Comment by cjhskippy** [comment]
Closed - no longer doing the non-interactive view.
