### ISSUE TITLE
Create intro text on CARTS homepage to test with state users

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-carts-seds#263]
As a **state user**, I need to **orient myself to a new system and understand what to expect** so that I can **use CARTS effectively and know where to go if I need help.**

- [ ] [Finalize intro text](https://docs.google.com/document/d/1WfXIuozNowFzwBSw4Lk1bEuZ6ER3kQbJdsn7Mpu66xs/edit#)

Screenshot of where text would go
![image](https://user-images.githubusercontent.com/23194720/89196688-8e650b80-d578-11ea-9a26-b5c576fed1a5.png)

**Comment by jgillis1** [comment]
@austinhernandez @erinzstrenio Is this ready for build out?
