### ISSUE TITLE
Migrate Existing State Users

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [18F/cms-carts-seds#266]
As Dev/Sec/Ops support person, I need to be able to migrate existing CARTS users to the new CARTS application.

AC:

- [ ] All existing users are activated in new CARTS

- [ ] All existing users are given the appropriate User Role in new CARTS

- [ ] All existing state users are associated with the correct state 

- [ ] Any new state users that were granted the CARTS_P_User job_code during the transition phase should be added (@jgillis1 will have this list)

**Comment by jgillis1** [comment]
Closing. Will used #720 instead.
