### ISSUE TITLE
Help Desk Support

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [18F/cms-carts-seds#269]
As a CARTS user if I can view my profile information and see a note that if it is incorrect, I should email the help desk.

AC:
- [x] User can see the following profile information:
  - Name
  - Email
  - State (if applicable)
  - Role in CARTS
  - EUA ID
- [x] User can see a link to point them to the help desk

**Comment by StephanieCoppel** [comment]
***banner/in-line vs. just a note that says contact the helpdesk with link?

**Comment by TaraWilliamsPGH** [comment]
@TGriesemer - when reviewing this I cannot see my email address as populated (there is a field for it) - I don't know if this is a Tara's profile/way I am set up issue, or if it is not showing for anyone. Can you confirm before I move it to close?
