### ISSUE TITLE
Define document statuses for technical requirements and for user comprehension. 

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-carts-seds#272]
As a **state or federal user**, I need to **understand what the different document statuses are** so that I can **move forward accordingly.**

As a **developer**, I need to **know what information to collect and display** so that I can **label the document in all phases of work.**

In the last rounds of usability testing there was some confusion about the term `draft`. Users expressed the desire to see the "level of completeness" of a report, but we have determined this is not technically feasible, nor will it drastically improve workflow or efficiency. We've also uncovered a workflow behind the `uncertify requested` status and uncertify workflow. Between what is technically feasible and user comprehension and impactful action, we need to list all of the potential phases of a document, how that information is assessed and clear actions a user can take with this information. 

- [ ] Define universally understood document nomenclature for state and federal users 
- [ ] Clearly layout the technical requirements for capturing and displaying varying document statuses. 
- [ ] Understand what actions a user can take based on this information. 
- [ ] Develop new workflow of uncertifying.

**Comment by austinhernandez** [comment]
https://docs.google.com/document/d/1KfMqcqCMhUvtQFZR9PY2vzpEjaF-5kcv51w4_-vyOKA/edit#

**Comment by StephanieCoppel** [comment]
****NEED TO DISCUSS AT 8/27 SPRINT PLANNING TO ENSURE ALL ASSOCIATED WORKFLOW STORIES ARE CREATED****
