### ISSUE TITLE
Prototype: Update 2B Objectives

### ISSUE THREAD

**Issue by cannandev** [18F/cms-carts-seds#276]
If we're going to have state user testing, we should make the following updates:

Prefill 2B objectives for all states with:

- Reduce the number of uninsured children
- Increase access to care
- Increase use of preventative care

First objective: 
* Should be numbered?
* Says "what is the first objective / Should say "what is another objective"

Noninteractive Review view:
Remove "Add" button functionality. 3 collapsed blank objectives? No prefilled objectives?

Print view/Export:
Expands everything all the time.

Report view: 
If empty, nothing

**Comment by cannandev** [comment]
Related to #274

**Comment by TaraWilliamsPGH** [comment]
@cannandev - can you provide the team clarification on this ticket? We are uncertain what milestone this belongs to and if it will require pointing.

**Comment by cannandev** [comment]
@TaraWilliamsPGH This isn't for the team just yet. I'm ironing out details of what we need for the next round of user testing. with Austin and Erin
