### ISSUE TITLE
Audit Logging for Continuous Monitoring

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [18F/cms-carts-seds#279]
As a CMS / IT Security user of CARTS, I need to be able to create audit logs and then push them to the appropriate CMS repository within the extension of the CI/CD process.
 (Cloudwatch to Splunk)
AC:

- [x] Database logs are sent to continuous monitoring site

(Related to #145?)

**Comment by jgillis1** [comment]
After talking to @dwhitecl, we are waiting for Will (CMS) to get the Splunk job code in EUA. Once he has that, we can ask the Splunk team to subscribe to our logging location on AWS CloudWatch.

@StephanieCoppel reached out to Will about the job code on 9/3/2020.

**Comment by StephanieCoppel** [comment]
Kaitlin Devine (CMS) submitted the request for the job codes yesterday (9/4) and they should be approved in the next few days

**Comment by jgillis1** [comment]
This was completed with JIRA Issues [OY2-252](https://qmacbis.atlassian.net/browse/OY2-252) and[OY2-313](https://qmacbis.atlassian.net/browse/OY2-313)
