### ISSUE TITLE
Build HTML prototype for user testing

### ISSUE THREAD

**Issue by cannandev** [18F/cms-carts-seds#28]
### Sections
- [x] Homepage
- [x] Section 2b
- [x] Section 3c

### Requirements:
Build an HTML clickable prototype using the CMS Design System for user interviews. This will be an iterative process;  we need to make changes to the components/content structures as we get feedback from users. 
Although the codebase will be in the private (Enterprise) repository, _this should be a public facing URL_.

### Dependencies: 
* [CMS Design System](https://design.cms.gov/)
* CI/CD
* Node and SCSS
* Snapshot tests using [Jest](https://jestjs.io/)
* [airbnb style linting](https://engineering.18f.gov/javascript/style/)
* [Accessibility checks](https://engineering.18f.gov/accessibility-scanning/) using Pa11y
* access to gsa.invisionapp.com
* ~enable Inspect mode in invision~

### Design
Form (2b, 3c)- https://gsa.invisionapp.com/share/6CWTUB9R3XN#/screens/417945156
Home - https://gsa.invisionapp.com/share/6CWTUB9R3XN#/414169264_CARTS_Home

### Components and Content Structures
[spreadsheet](https://docs.google.com/spreadsheets/d/1mCzbOGkNnx6i_e05cl-GxzzQKEqJOpFT4XAtlLjpqPs/edit#gid=573545140)

### Engineering Best Practices
https://engineering.18f.gov/

**Comment by jgillis1** [comment]
@cannandev @tadhg-ohiggins 
With your agreement, I would like to close this issue out.
