### ISSUE TITLE
Table Validation

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [18F/cms-carts-seds#282]
As a state user I need to that the data I enter into tables is valid so that I know if my responses are accurate.

AC:

- [ ] Contents of table are validated appropriately (this will change after design has been decided)

**Comment by TaraWilliamsPGH** [comment]
@cannandev is this a part of the validation of inputs as a part of the 3c table data? if so, can this one be closed?

**Comment by cjhskippy** [comment]
Removed from milestone Hummingbird Cake - was removed from scope, so should not appear on sprint reports.
