### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [18F/cms-carts-seds#300]
As a CARTS user I need to be able to log into the application so I can do my job.

AC:

- [x] Login accepts user credentials (handled by OKTA; we need to manage credentials on the DB side to understand level of permissions)

- [x] Validates user permissions (type of user pulled from DB)

- [x] Directs user to appropriate homepage landing (meaning state user, central office, invalid user, etc)

**Comment by cjhskippy** [comment]
Taking notes here about some other important considerations, even if we decide to put them in one or more separate stories:

- [ ] What's the UX for failed logins?
- [ ] Where a user can get help if their login isn't working

**Comment by TaraWilliamsPGH** [comment]
NOTE: Laura/Seth have already done some work on this...please verify first.

**Comment by mgwalker** [comment]
@tadhg-ohiggins Are you currently working on the UI part of this? If not, I can pick it up.

**Comment by tadhg-ohiggins** [comment]
@mgwalker Nope, all yours
