### ISSUE TITLE
2B Goals and Objectives Design

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [18F/cms-carts-seds#305]
As a CARTS user I want to be able to easily add/remove goals and objectives for my state so that I can manage the process year over year more effectively. 

If we're not able to dynamically display data in time for the usability test, use the following as Acceptance Criteria for the prototype:
- [ ] Show 3 prefilled objectives 
- [ ] Show 3 blank objectives 
- [ ] Accordions should be closed initially
- [ ] Update text for new objective
- [ ] Add ability to delete (see eapd) #287 

**Prefilled objectives:**
1. Reduce the number of uninsured children
2. Increase access to care
3. Increase use of preventative care

**Update text for new objective:**
When user clicks Add Objective, the initial question should read:
`what is another objective`
instead of `"what is the first objective`

Eventually add new objectives in the Prototype code using the new **Repeatables** component

**Comment by tadhg-ohiggins** [comment]
The data structure for each objective has a question one, which is the describe your objective question, but this is hidden in the very first objective, which is a special case. When a new objective is created, that question is shown.
The contents of that question's answer populate the header for the objective.
In the case of the first objective, the header is populated by the `default_entry` property's value of that question's data structure.
Other aspects of creating a new goal or objective are covered here https://github.com/18F/cms-carts-seds/blob/master/docs/section-schemas/backend-json-structure-documentation.rst#objectives

**Comment by TaraWilliamsPGH** [comment]
Ticket closed because this work was already completed.

**Comment by cjhskippy** [comment]
It's not exactly clear which sprint this was completed in; moving to milestone Funfetti as the most likely completion.
