### ISSUE TITLE
Update program names in Basic Info section

### ISSUE THREAD

**Issue by erinzstrenio** [18F/cms-carts-seds#306]
Question 2 in the Basic Info section should be updated based on the feedback we heard from federal users. (It's still the same three options just spelled out instead of the M-CHIP/S-CHIP shorthand)

2. Program type:   
 Combination
 Medicaid Expansion CHIP only
 Separate CHIP only 

https://docs.google.com/document/d/1iTknG0tSWgInm28BFIdq1KnwdLdH57UJIa6cPbQjn5A/edit

**Comment by jgillis1** [comment]
@tadhg-ohiggins Could you update the JSON for Section-0 accordingly?

**Comment by tadhg-ohiggins** [comment]
Addressed in pull 320
https://github.com/18F/cms-carts-seds/pull/320/files#diff-2325750ef1673c8b728bbc6033496c93R39

**Comment by tadhg-ohiggins** [comment]
Fixed by #320
