### ISSUE TITLE
Rethinking flow of CARTS sections

### ISSUE THREAD

**Issue by erinzstrenio** [18F/cms-carts-seds#31]
https://app.mural.co/t/gsa6/m/gsa6/1583273959166/397209461c3174d6434ff7b6e04a5aeaafc1fc80

Rearranging CARTS sections based on: 
a) Card sorting calls with state users a few months back
b) how POs ranked the usefulness of different sections 
c) how applicable each section is to the various programs (Combo/M-CHIP/S-CHIP)

**Comment by erinzstrenio** [comment]
@TaraWilliamsPGH I was keeping this open until we renumber the sections. Right now we're still referring to them by the old section numbers. Is there another ticket that would reflect that update?

**Comment by TaraWilliamsPGH** [comment]
No @erinzstrenio we do have a label we created to not lose site of these items for V2 - I will add this tag.
