### ISSUE TITLE
Request New EUA Job Codes

### ISSUE THREAD

**Issue by jgillis1** [18F/cms-carts-seds#329]
We need to request 3 additional Job Codes be created in EUA that will be for CARTS Administrators (BOs, Help Desk, Development Team Staff, etc.)

Job Code                  Description                                          
CARTS_P_Admin     Administrator role for CARTS Production User
CARTS_V_Admin     Administrator role for CARTS Validation User
CARTS_D_Admin     Administrator role for CARTS Development User

**Comment by StephanieCoppel** [comment]
this is completed and i will close
