### ISSUE TITLE
“Hello World” on live public domain

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/cms-carts-seds#35]
- [x] Come up with a domain name. My suggestion is `cartsdemo.cms.gov`.
- [x] Create the AWS instance/environment for this domain.
- [x] RDS Postgres as the DB, Django with EC2 as the backend, React for the frontend (frontend possibly served via S3?). Also a load balancer, which IIRC isn't much of an addition in AWS. CloudFront distribution for the frontend.
- [x] CI/CD to let us push to this environment from Github, with various test/linting/etc. suites as part of this process.
- [x] These don't need to be working together for the Hello World issue—we just want to be able to push a static page to a public domain at first, and then add the other components over time.

**Comment by tadhg-ohiggins** [comment]
@jgillis1, assigning you here as I think you'll know how to route this.

The important things to actually finish by the end of Angel Cake are the first and last—we should choose the domain name, hopefully have it pointing at something, and have that something be Hello World by the end of the sprint.

**Comment by jgillis1** [comment]
@tadhg-ohiggins We are going to need to push this out to Babka due to the time it takes to get the certs and dns processes. The certs take 5-10 days and dns will be a few days as well.

**Comment by jgillis1** [comment]
@dwhitecl has confirmed [cartsdemo.cms.gov](cartsdemo.cms.gov) is up and running
