### ISSUE TITLE
Section 1 Part 3 Question 21 is conditional

### ISSUE THREAD

**Issue by jgillis1** [18F/cms-carts-seds#350]
In section 1, Parts 3 and 4, Question 21 for both parts should only display if a "yes" answer occurs.

For both Parts 3 and 4 in Section 1:
- [ ] Question 21 does not display if all responses to questions 1-20 are "no" for the Part
- [ ] Question 21 displays if there is any "yes" response to questions 1-20 for the Part

Implementation note:
- Update JSON so Question 21 is conditional

**Comment by jgillis1** [comment]
@tadhg-ohiggins This is a situation where the conditional is based on the outcome of multiple questions. We can work with you on this but editing the JSON here may be outside of our capabilities at the moment (though if you can give us steps, we can follow them). Definitely not as high a priority as the User Auth stuff.

**Comment by cjhskippy** [comment]
Moved the part about listing "yes" answers into #506 which we can push a little lower on our priority list.

**Comment by alewoo28** [comment]
I want to clarify, are we waiting for the JSON to change in order to implement this or are we making a hard-coded workaround on the frontend for this specific question.
