### ISSUE TITLE
Replace current CARTS header with intro text for 8/20 demo.

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-carts-seds#358]
The current header was confusing in usability testing. We are replacing the current CARTS header:
<img width="1076" alt="Screen Shot 2020-08-14 at 10 56 16 AM" src="https://user-images.githubusercontent.com/23194720/90262874-e1fb1300-de1c-11ea-9fe3-e8923bb721e6.png">

...with the welcome text below:

```
<h1> CHIP Annual Report Template System (CARTS)</h1>
<subhead> Welcome to CARTS! We’ve incorporated feedback from several states to bring you a better CARTS experience. Contact <a href="mailto:CARTSHELP@cms.hhs.gov?subject=CARTS Help request">CARTSHELP@cms.hhs.gov</a> with any questions. </subhead> 
```

Ideally, this would be done for the demo page for Thursday's 8/20 interview.

**Comment by erinzstrenio** [comment]
@austinhernandez the subhead message you posted here would replace the lorem ipsum text, is that correct? 

Let's also update `FY20 template is ready for download` to be:  
`CARTS FY 2020 report is ready to download`

Do we know whether states refer to `Central Office` as such? if not, maybe we confirm this in the usability testing (to make sure that header makes sense?)

**Comment by austinhernandez** [comment]
Sorry Claire, this is more clear and annotated

<img width="1076" alt="90262874-e1fb1300-de1c-11ea-9fe3-e8923bb721e6" src="https://user-images.githubusercontent.com/23194720/90804201-e07f8e00-e2e7-11ea-96ae-38dfb6907445.png">
