### ISSUE TITLE
Change the column labels on the State User homepage

### ISSUE THREAD

**Issue by austinhernandez** [18F/cms-carts-seds#367]
Please change the column names and structure on the State User homepage.

![CARTS state home](https://user-images.githubusercontent.com/23194720/90571704-549f2200-e180-11ea-8c50-16521446fb53.png)

Annotated: 
![a-CARTS state home](https://user-images.githubusercontent.com/23194720/90571726-5ff24d80-e180-11ea-83bc-ab393a779102.png)

- [x] Year instead of Name
- [x] Last edited includes the name of the user who last edited
- [x] Show 5 documents instead of 10

Notes:
- In preliminary usability interviews, a majority of users mentioned changes from the previous year being very beneficial in their workflow. If there is an opportunity for Overview of Changes page, we would love to have the sentence: `Check out the “Overview of Changes” page for a rundown of the major changes we’ve made.` Added to the intro text with a link to a page that has things that have changed. For V1, we understand this might be an email.

**Comment by austinhernandez** [comment]
Blocked by #272

**Comment by cannandev** [comment]
@austinhernandez Just a note that we don't have previous year data mapped with the same structure. So we can't edit previous year reports.

**Comment by cannandev** [comment]
@austinhernandez Just double checking....we want the **Last Edited by** to be displayed as [Karen Dalton](aren.dalton@state.gov) or [karen.dalton](karen.dalton@state.gov)?
