### ISSUE TITLE
Build of Section 5 

### ISSUE THREAD

**Issue by erinzstrenio** [18F/cms-carts-seds#381]
Blocked by issue #518 

As a user, I want to be able to see the questions in section 5 and save my answers.

- [x] Section 5 appears in the navigation bar
- [x] All form content in section 5 displays per [design document](https://docs.google.com/document/d/1N3wgjF4VwMd9HXG7F8xYS13nswctSC03c41HkvGMOus/edit#).
  - [x] Includes column for projected years (get question # this applies to)
- [x] Users can save answers that will be retained when navigating to other parts of the form (e.g. saved in the Redux store)
- [ ] Updates are deployed to the cartsdemo site + pass UAT w/ Stephanie.

Engineering Notes as of 9/25:
- the JSON is probably incorrect for the help text - 
- Completing all of this section may require PR #632 being merged
- if the `show_if` functionality got merged, there’s a question in that section that should be slightly redone in the JSON to make it appear only if other is selected in the checkboxes

Content notes: 

- [x] Add gridview tables for 2020, 2021, 2022 and synthesized tables should have columns for all three years. We consolidated all three years into the questions, so there are now fewer parts and tables. [See content doc](https://docs.google.com/document/d/1pyCyUQPJKVEIKZ3cBTM8ZThxNeLiUzIKPPr0xfImtv4/edit?ts=5f6cea35#) for updates. 

Related to issue #214

**Comment by kaitlin** [comment]
I've started a build out of this on branch `new-section-5`.

**Comment by jgillis1** [comment]
@kaitlin Could you confirm, this ticket is up for grabs to any developer? They can just start with your branch and move forward.

**Comment by erinzstrenio** [comment]
I'm happy to pair with @kaitlin or any other dev who picks this up! The [template doc](https://docs.google.com/document/d/1pyCyUQPJKVEIKZ3cBTM8ZThxNeLiUzIKPPr0xfImtv4/edit?ts=5f6cea35#heading=h.xrab6krx0pon) is the best one to reference for updated language per DSCP edits.

**Comment by andrewadcock** [comment]
Section 5, Part 2, Table 3 relies on FMAP data that currently isn't available. I believe this work has started but may need to be modified so that we can use it with a synthesized table and RPN (i.e. add an ID).

In addition, there is a complex equation which requires multiplying against a sum: FMAP (FFY 2020) x [total program costs]
