### ISSUE TITLE
Build certify and submit

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#385]
As a state user, upon filling out the entirety of the CARTS form, I want to certify my report and submit it for CMS review.

AC:

- [x] User is able to navigate to the "Certify and Submit" tab after Section 6

- [x] User is able to read the text (see diagram below: "Ready to Submit" portion only) and select the "Certify and Submit" button

- [x] User receives a response from the application that states "Thank you"and let's user know what to expect next  (see Austin's second diagram below) 

- [x] This should only be visible to users who have the ability to certify and submit a form; those that do not have this level of access WOULD NOT see the certify and submit tab (they would see the "previous" button only because that is the end of their view)

- [ ] all CHIP Project officers have the ability to certify and submit, but this action should ONLY be available to them if they are viewing a report for a state associated with their profile

- [x] Done button takes you to homescreen

**Comment by austinhernandez** [comment]
annotated screens

This screen is seen when a document has not yet been certified.
![CARTS review and submit-1a](https://user-images.githubusercontent.com/23194720/92526312-437f8900-f1f3-11ea-803e-d52f94c8d8b2.png)

This screen is seen after a document has been submitted and/or is no longer editable.
![CARTS review and submit-2a](https://user-images.githubusercontent.com/23194720/92526317-44181f80-f1f3-11ea-85ae-8759ee1904b5.png)

content doc here: https://docs.google.com/document/d/1cCUtj1fiHd9HxNVknyHwKLiorT428NQ5G5AMLMDr8qA/edit#
