### ISSUE TITLE
Create a master Questions Component

### ISSUE THREAD

**Issue by jgillis1** [18F/cms-carts-seds#409]
Create a component that can be called by any page and contains all the implemenations of the various Question and Answer types the CARTS for uses.

Input types to handle:
- [x] integer
- [x] ranges
- [x] email
- [x] text (same as text_long)
- [x] text_small
- [x] text_medium
- [x] text_multiline
- [x] radio
- [x] checkbox
- [x] phone_number
- [x] daterange
- [x] percentage
- [x] checkbox_flag
- [x] money
- [x] file_upload

(Note from @cjhskippy: the following field types will be implemented as components that will be tracked in separate tickets.  A part of each of those tickets will need to include updating the master questions component, but that work can be tracked outside of this issue.

- [ ] ~~fieldset - marked~~
- [ ] ~~fieldset - with label~~
- [ ] ~~datagrid_with_total~~
- [ ] ~~synthesized_table~~
- [ ] ~~synthesized_value~~
- [ ] ~~noninteractive_table~~
- [ ] ~~objectives~~
- [ ] ~~goals~~
- [ ] ~~repeatable~~
- [ ] ~~repeatables~~
- [ ] ~~select [there's only one "2020-00-a-01-01"]~~

(list courtesy of @cannandev)

**Comment by mgwalker** [comment]
@alewoo28 @andrewadcock @TGriesemer Would one of y'all mind verifying which of these are already covered by the question component?
