### ISSUE TITLE
update Section 1 per DSCP feedback

### ISSUE THREAD

**Issue by erinzstrenio** [18F/cms-carts-seds#415]
Any "Yes" responses should prompt users to enter details for why changes have been made

When section 1 renders, the additional children must also render.

AC:

- [x] Consult with Erin

- [ ] Change JSON

- [ ] Update components as needed

**Comment by cannandev** [comment]
BTW, the "State or territory name" field should be "select" or "dropdown". Right now it's "text"

**Comment by erinzstrenio** [comment]
@cannandev do you mean for the Basic Info page or Section 1?
