### ISSUE TITLE
Pen Test Architecture Diagram 

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [18F/cms-carts-seds#422]
AC:
Diagram complete containing the following details:

- [x] Host Names

- [x] IP Addresses

- [x] Port Numbers

- [x] Services

- [x] Software

- [x] Answers the question: How does the data flow?

**Comment by jgillis1** [comment]
From John D.: architecture diagram is very technical...has all of the server information listed, including type, size etc...has the ip address....has versions of the apps running on each, port information for communications.

**Comment by dwhitecl** [comment]
@jgillis1  can I get more information on what is expected here?

**Comment by jgillis1** [comment]
@dwhitecl I added some Acceptance Criteria after talking to Eric. Is the diagram you made a while back still accurate? I re-emailed it to you on 8/27 to check.

**Comment by jgillis1** [comment]
This is with Eric Hill (ISSO) for final sign-off as of 9/25/2020.
