### ISSUE TITLE
Pen Test Systems Diagrams

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [18F/cms-carts-seds#423]
AC:

- [ ] Diagrams complete

**Comment by jgillis1** [comment]
From John D.: a systems/ talks about each server and the function they play, Portal, DB server, App server, has minimal technical details version of software mostly

**Comment by TaraWilliamsPGH** [comment]
@tadhg-ohiggins confirm with Eric Hill that what you already provided is sufficient.

**Comment by TaraWilliamsPGH** [comment]
Have ticket for architecture diagram in sprint. Not needed.

**Comment by cjhskippy** [comment]
Removed from milestone so does not affect sprint reports.
