### ISSUE TITLE
Write up a troubleshooting and disaster recovery document

### ISSUE THREAD

**Issue by ayushi-roy** [18F/cms-carts-seds#43]

**Comment by ayushi-roy** [comment]
- Please use plain language and with explicit directions that cover any troubleshooting or incident recovery steps for various scenarios
- Next: Do a disaster recovery drill on your test sites (Test your data backups, key rotation instructions, etc.)
- Use this drill as a way to model how to run a postmortem

**Comment by TaraWilliamsPGH** [comment]
Covered in ATO and part of security assessment documentation.
#154
