### ISSUE TITLE
Home Page Report List

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#434]
As a state user, I want to be able to view and edit my 2020 report.  Upon login, display the following content:

<img width="1146" alt="Screen Shot 2020-09-09 at 7 42 26 PM" src="https://user-images.githubusercontent.com/1299543/92675733-f542b680-f2d4-11ea-93ca-41d8a05412cb.png">

AC:
- [ ] Home page content appears per mockup
- [ ] Email displayed in welcome text is a mailto link to CARTSHELP@cms.hhs.gov
- [ ] All states have a blank 2020 report created in "In Progress" status
- [ ] State users see their 2020 report displayed with its year and status (note: we agreed this could be hard-coded for all states at this time)
- [ ] Edit link works and is displayed for the 2020 report

Per discussion in sprint planning, we are scaling this back.  The following behavior will be post-MVP and is out of scope:
- #565 (dynamically showing list of reports and their status)
- List behavior for CMS user and admin user are out of scope.
- Displaying prior year reports is out of scope.
- Pagination is out of scope.

**Comment by cjhskippy** [comment]
Related to #272

**Comment by StephanieCoppel** [comment]
**want to ensure at sprint planning that this story is appropriate size and the ACs listed are easy to complete
