### ISSUE TITLE
Date Range component uses API

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#440]
Update the Date Range component to read and write real data.

A/C:
- [ ] Date range component can accept earliest and latest dates in the format "from mm/yyyy to mm/yyyy"
- [ ] Component can read and write from the data store
- [ ] Master questions component is capable of rendering the date range component

QA notes:
- Affects sections 2a and 2b. Example: section 2a, question 3b

**Comment by jgillis1** [comment]
Occurs in Section 1, 2b & 3f
