### ISSUE TITLE
Fixtures for section 3g

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#468]
Ensure that, upon deployment to a new environment, the content for section 3G is loaded.  #356 must be completed first.

A/C:
- [ ] Upon deployment, the questions for section 3G on 2020 reports is populated in the database. 

Note: Work with Tony on CL side to get him up to speed

**Comment by jgillis1** [comment]
ROLLOVER NOTE: The content of 3G has changed several times during Sprint I, the most recent being in the evening on 9/23/2020. As of 8:52 AM 9/24/2020, Andrew needs final confirmation that he is interpreting and implementing the content changes made correctly.

Issues Raised:
- help_drawer

- checkbox about whether or not the State collects data via age ranges which then changes which table the State fills out
