### ISSUE TITLE
Fixtures for section 3h

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#469]
Ensure that, upon deployment to a new environment, the content for section 3h is loaded. #465 must be completed first.

A/C:
- [ ] Upon deployment, the questions for section 3h on 2020 reports is populated in the database.

**Comment by jgillis1** [comment]
@mgwalker Is this completed since you did the JSON for 3h?

**Comment by mgwalker** [comment]
Yep, good catch! Closed by #487
