### ISSUE TITLE
User Administration

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#488]
As a site administrator, I want to have the ability to manage user accounts so that I can ensure that all people who need system access have the correct state assignment, contact info, and permissions.
- [ ] Admin users can add users to the system
- [ ] Admin users can change the state associated with a user
- [ ] Admin users can change the user role for a given user
- [ ] Admin users can deactivate a user account
- [ ] Admin users can change the contact info for a user

*Note*: for a bare-minimum MVP, administrative access that requires high technical competence is okay.  Per @tadhg-ohiggins we may be able to meet this need quickly and adequately by using the built-in admin console for Django - update the Django interface to accept Okta authentication.

**Comment by StephanieCoppel** [comment]
split into smaller stories, closing this large story out
