### ISSUE TITLE
Update PRA Disclosure Statement Language on CARTS Form

### ISSUE THREAD

**Issue by StephanieCoppel** [18F/cms-carts-seds#491]
Replace current PRA Disclosure Statement Language on form with highlighted paragraph on page 2 of the attached document (copy/pasting into the ticket was creating errors in the ticket)

PRA Disclosure Statement. This information is being collected to assist the Centers for Medicare & Medicaid Services (CMS) in partnership with States with the ongoing management of Medicaid and CHIP programs and policies. This mandatory information collection (42 U.S.C. 1397hh) will be used to help each state meet the statutory requirements at section 2108(a) of the Social Security Act to assess the operation of the State child health plan in each Federal fiscal year and to report the results of the assessment including the progress made in reducing the number of uncovered, low-income children. Under the Privacy Act of 1974 any personally identifying information obtained will be kept private to the extent of the law. According to the Paperwork Reduction Act of 1995, no persons are required to respond to a collection of information unless it displays a valid OMB control number. The valid OMB control number for this information collection is 0938-1148 (CMS-10398 #1). The time required to complete this information collection is estimated to average 40 hours per response, including the time to review instructions, search existing data resources, gather the data needed, and complete and review the information collection. Send comments regarding this burden estimate or any other aspect of this collection of information, including suggestions for reducing this burden, to CMS, 7500 Security Boulevard, Attn: Paperwork Reduction Act Reports Clearance Officer, Mail Stop C4-26-05, Baltimore, Maryland 21244-1850.

**Comment by StephanieCoppel** [comment]
[https://app.zenhub.com/files/226399669/9317fff9-6cfc-4607-bd6f-6fb5025f6a72/download](https://app.zenhub.com/files/226399669/9317fff9-6cfc-4607-bd6f-6fb5025f6a72/download)

**Comment by cjhskippy** [comment]
Does this disclosure text need to be center-justified?  Not a big issue, but seems like it would be better left-justified.

**Comment by jgillis1** [comment]
@StephanieCoppel Do you have a justification preference here? Center? Left?

**Comment by StephanieCoppel** [comment]
left is great, thank you

**Comment by jgillis1** [comment]
@andrewadcock Could you change the justification on this to Left, please?

**Comment by andrewadcock** [comment]
I was informed that the PRA Disclosure should actually go under the form on the Basic Info page. There is a PR in place now for that. Given that we are reverting to the shorter copy of the OMB info, do we still want this left justified?

**Comment by erinzstrenio** [comment]
@andrewadcock left justified is good 👍
