### ISSUE TITLE
Add document status to JSON/API/DB and input locking to overall system.

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/cms-carts-seds#496]
As a CMS user, I want states to be unable to make changes to their reports after certifying them so that I can review the report accurately.

This is most important for certified status, because once a state's submission is certified, the application needs to know because the state is then no longer permitted to make changes; changes can only be made when a submission has a status other than certified.

A/C:
(needs detail)
- Frontend does not display an option to edit documents when their status does not allow it
- API should reject attempts to change documents that are in a status that does not allow edits.

Engineering notes:
Support for reading report status should be added in #418 .  There is currently no support for writing document status. Depends on #418.

**Comment by StephanieCoppel** [comment]
@tadhg-ohiggins  is this story still relevant/accurate, and/or is it covered somewhere else? just want to confirm before I put it in an upcoming sprint
