### ISSUE TITLE
Pilot legal process: Section 2B

### ISSUE THREAD

**Issue by ayushi-roy** [18F/cms-carts-seds#50]
Share with Kaitlin to start conversation with legal team.

**Comment by erinzstrenio** [comment]
Here's the google doc with the updated content in 2B, approved by legal: https://docs.google.com/document/d/1I-pnJCrsceEaIoFjHMQOqApQBBdyPj2e7Olqc0nK_eI/edit

I believe this one's ready to close? @ayushi-roy
