### ISSUE TITLE
Revise Preamble + Basic Info sections

### ISSUE THREAD

**Issue by erinzstrenio** [18F/cms-carts-seds#51]
- [x] Revise preamble content
- [x] Revise "tell us your basic info" content
- [x] Hand off content to CL
- [x] Add territories to dropdown menu @cannandev 
- [x] Fix content typos

**Comment by ayushi-roy** [comment]
Add DC to dropdown

**Comment by cannandev** [comment]
Fix typos in content:
sentence case (eg. _Territory_ should be _territory_) 
add colons at the end of labels 
program type should be second, not third question 

Please check the latest content document
https://docs.google.com/document/d/1iTknG0tSWgInm28BFIdq1KnwdLdH57UJIa6cPbQjn5A/edit
