### ISSUE TITLE
Display Section 6 (includes moving section 5 content)

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#518]
As a user, I want to be able to see the questions in section 6 and save my answers.

- [x] Section 6 appears in the navigation menu.
- [ ] All form content in section 6 displays per [design document](https://docs.google.com/document/d/1R6e3ZWL-Xc1TG2GBW4XFe4peCFCX4uyDYMbH9fX3CPM/edit#).
- [x] Users can save answers that will be retained when navigating to other parts of the form (e.g. saved in the Redux store)
- [ ] Updates are deployed to the cartsdemo site + pass UAT w/ Stephanie.

Engineering notes:
The final designs have different section organization from our prototype.  All of the content currently saved in the JSON as section 5 should actually be placed into section 6.

Includes these subtasks:
- [ ] #467 - Update the JSON to make the current "section 5" content section 6.
- [ ] #471 - Update the fixtures so that section 6 is automatically populated on any new push to the database.

**Comment by jgillis1** [comment]
JSON will need updating as of 9/17/2020.

**Comment by cjhskippy** [comment]
Specific update:
- [ ] Question 4 is moved to Question 5.
- [ ] A new question 4 is added `What changes have you made to your CHIP program in the last FFY or plan to make in the next FFY? Why have you decided to make these changes?`
