### ISSUE TITLE
Add Preamble + Basic Info Section to HTML Prototype

### ISSUE THREAD

**Issue by jgillis1** [18F/cms-carts-seds#52]
- [x] Preamble
- [x] Basic Information
- [x] Set the Edit link for the 2020 form on the Home page to go to the Preamble

See #28 for additional Requirements & Details

Mock Up: https://docs.google.com/document/d/1iTknG0tSWgInm28BFIdq1KnwdLdH57UJIa6cPbQjn5A/edit?ts=5eda8bba

**Comment by jgillis1** [comment]
https://docs.google.com/document/d/1iTknG0tSWgInm28BFIdq1KnwdLdH57UJIa6cPbQjn5A/edit?ts=5eda8bba

**Comment by cannandev** [comment]
Adding these issues as discussed in our code review:
- [ ] **Logout dropdown** should close when clicked outside.
- [ ] Homepage **report list** should use [grid component](https://design.cms.gov/layout/grid/) instead of a table
- [ ] **Accordion header** click should open _and close_ component. 
- [ ] Enable **hover "Same as last year"** functionality (should be able to access latest sketch file)

**Comment by cannandev** [comment]
@andrewadcock Let me know if this works for the hover-copy icon!
![copy](https://user-images.githubusercontent.com/381122/84707517-d7132780-af2c-11ea-8e83-9108a883fca5.png)

**Comment by cannandev** [comment]
Looking good! Here is some feedback on these two sections. 

**General**
- [ ] Add left margin (2em) to basic sections `.ds-base`. Leave sections with tabs as is (2b, 3c).
- [ ] Replace Preamble and Welcome! titles with a new state info component, as discussed

**Preamble** (See design attached)
- [ ] Add Next and Saved buttons to bottom of sections
- [ ] Add H3 headings before bulleted lists
- [ ] Indent bulleted lists


**Basic Information**
- [ ] Add numbers to Contact information fields (4-8)

Thanks!

![carts-preamble](https://user-images.githubusercontent.com/381122/84863384-d79de200-b042-11ea-8134-797ce1c50d84.png)

**Comment by jgillis1** [comment]
@cannandev Is 1 Phone Number field enough or should there be options for like Office/Main and Cell?

**Comment by cannandev** [comment]
> @cannandev Is 1 Phone Number field enough or should there be options for like Office/Main and Cell?

@jgillis1 I think 1 phone number field is enough. Tagging @erinzstrenio just to be sure.

**Comment by erinzstrenio** [comment]
@jgillis1 @cannandev yep, I think 1 phone number field is sufficient!
