### ISSUE TITLE
FY2020 FMAP Rate 

### ISSUE THREAD

**Issue by StephanieCoppel** [18F/cms-carts-seds#522]
As a state user, I want to see the FMAP rates that apply to my state when filling out section 5 (formerly section 4) of the CARTS form.

The FMAP rate varies per state per year.

For this story, we just want to be able to *display* the correct FMAP rate for 2020 in section 5 (formerly section 4)  of the form.  This data will be pre-populated by the dev team, and not editable by users.  Per Tadhg's notes:

-  Add location in Redux Store for FMAP rate. Should be linked to info about the state/state program.
-  Add DB spot for FMAP rates.
-  Add API read endpoint
-  Get FY2020 data. Include it in deployment scripts.

A future release will include DSCP ability to enter these themselves for FY2021 release (#476)

AC: 
- [ ] State users see the correct FY2020 FMAP rate for their state in section 5 (formerly section 4) of the CARTS form

**Comment by StephanieCoppel** [comment]
FMAP rates to be input into the application at link below (scroll down to see the FY2020 rates for each state):
https://www.federalregister.gov/documents/2019/12/03/2019-26207/federal-financial-participation-in-state-assistance-expenditures-federal-matching-shares-for

**Comment by erinzstrenio** [comment]
@StephanieCoppel do you know if the FMAP rates should be pulled from the first or second column from that link?

**Comment by erinzstrenio** [comment]
also just capturing here that DSCP will need to add 2021 FMAP rates onto the 2020 report once they're made available (I believe October?) since states will need to enter their projected 2021 costs onto the 2020 report

**Comment by StephanieCoppel** [comment]
enhanced FMAP rates should be used (the second column) @erinzstrenio

**Comment by kaitlin** [comment]
I submitted a PR for the backend work (bullets #2-4) but the front-end work here to pull it into Redux still needs to happen.
