### ISSUE TITLE
Report Statuses for Release

### ISSUE THREAD

**Issue by StephanieCoppel** [18F/cms-carts-seds#523]
In progress

As soon as the template is available and before it’s submitted
Includes timestamp of last edit and last user to edit

AC:
[ ] When viewing the home screen, for the appropriate status would appear in the status column next to each year's report ( #434 )
[ ] When a CARTS report is available for editing/completion but not yet submitted for certification, it will be in the "in progress" status (included in #434)
[ ] Display document statuses within sections ( #418 )

**Comment by cjhskippy** [comment]
After cleaning up #418 and #434, I think we can close this as a duplicate; the AC for this story are incorporated into the other two.
