### ISSUE TITLE
Update JSON for Section 3C

### ISSUE THREAD

**Issue by cannandev** [18F/cms-carts-seds#537]
Update content in JSON

Updated Google doc: https://docs.google.com/document/d/1pyCyUQPJKVEIKZ3cBTM8ZThxNeLiUzIKPPr0xfImtv4/edit#

**Comment by mgwalker** [comment]
@TaraWilliamsPGH I suspect this can be closed? @erinzstrenio  has done a lot of work getting the content updated in the last sprint and I bet that includes 3C.
