### ISSUE TITLE
Display helper text

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#539]
Several form sections include "helper text" that provides context just after a section heading or question.  That text is not currently appearing on the form.

A/C:
- [ ] When users load a page with helper text, it displays in the specified parts of the report.  Examples in section 3h ([design doc](https://docs.google.com/document/d/1_5gBq_96gz3kQ_yQdt09SXI_0Oy8YO5i5YFZZEiGCmk/edit#)):
  - ~~Text underneath the main section header isn't displaying: `Children’s Health Insurance Program Reauthorization Act (CHIPRA) requires that all CHIP programs submit survey results from the Consumer Assessment of Healthcare Providers and Systems (CAHPS). The survey assesses your CHIP program quality and customer satisfaction.`~~ (fixed!)
  - ~~Text directly under the Part 2 subheading isn't displaying ( `If you’ve collected CAHPS survey results, complete Part 2. If you’ve already submitted CAHPS raw data to the AHRQ CAHPS database, Part 2 is optional.` )~~ (text changed, but also fixed!)
  - ~~The help text accompanying Part 2, question 1 is not displaying (`Submit results only for the CHIP population, not for both Medicaid (Title XIX) and CHIP (Title XXI) together. Your data should represent children enrolled in all types of delivery systems (Managed Care, PCCM, and Fee for Service).`)~~ (fixed!)

Engineering notes:
- The helper text is included in the JSON.  It should be retrieved from the API and displayed via a reusable component.

**Comment by andrewadcock** [comment]
It looks like the JSON isn't returning Part titles or helper text. Adding dependency for #555.

**Comment by cjhskippy** [comment]
Added a third example from section 3h.

**Comment by cjhskippy** [comment]
Reopened.  Examples 2 and 3 in the acceptance criteria are not resolved.

**Comment by jgillis1** [comment]
Note: The "hint" from the JSON isn't in the QuestionComponent so the hints/helper text isn't displaying.

**Comment by cjhskippy** [comment]
These all look resolved to me.  I think we can mark it closed.
