### ISSUE TITLE
No Man's Land Page Gap

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [18F/cms-carts-seds#558]
Section 3E - goes from item 11 to 22, either missing questions or the notification for skipped questions is missing.

**Comment by mgwalker** [comment]
@TaraWilliamsPGH @cjhskippy @StephanieCoppel Can one of you confirm this is still an issue? I just sat down to work on it and it looks like it may have been fixed.

**Comment by StephanieCoppel** [comment]
i dont see it either!!! must have been fixed with some of the earlier work, you can go ahead and close this. wooo!
