### ISSUE TITLE
Section 3h: questions that should be multi-select instead of radio buttons

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#567]
In section 3h, users should be able to select more than one option for Part 2, questions 4 and 5. (see [design doc](https://docs.google.com/document/d/1_5gBq_96gz3kQ_yQdt09SXI_0Oy8YO5i5YFZZEiGCmk/edit#) for reference):

A/C:
- [ ] Part 2, question 4 is multi-select.
- [ ] Part 2, question 5 is multi-select.

**Comment by jgillis1** [comment]
@cjhskippy this appears to be resolved as part of #578. Could you confirm?
