### ISSUE TITLE
CMS Windows users unable to access demo site

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#597]
@StephanieCoppel and another CMS colleague were both unable to access https://mdctcartsdev.cms.gov/sections/2020/0?dev=dev-ak and https://cartsdemo.cms.gov/sections/2020/0?dev=dev-ak from their CMS-issued computers.  The error message indicates a possible DNS issue.

Users from 18F and Collabralink are both able to access these websites.  We believe Kaitlin is as well, which may indicate that the issue is specific to users on Windows systems at CMS.

A/C:
- [ ] Stephanie is able to access https://cartsdemo.cms.gov/sections/2020/0?dev=dev-ak and https://mdctcartsdev.cms.gov/sections/2020/0?dev=dev-ak

**Comment by jgillis1** [comment]
I have reached out to Doug and Nathan. Nathan indicated the message means an internal CMS DNS update needs to happen and he will circle back with the CMS team on that. 

In the interim, if Stephanie is off of the CMS VPN, she should be able to access the site.

**Comment by StephanieCoppel** [comment]
eAPD encountered the same issue and i am currently resolving with the help desk, everyone else can stand down. thank you!!!!!

**Comment by TaraWilliamsPGH** [comment]
This is irrelevant at this point, potentially.
