### ISSUE TITLE
JSON & Fixtures for Section 4 (formerly section 2B)

### ISSUE THREAD

**Issue by jgillis1** [18F/cms-carts-seds#606]
Ensure that the content for section 4 is represented in JSON. This section is a special case: Section 2B was so big that designs indicated we should make it a section by itself.  The JSON for this section already exists, but we will need to move it.  Related to #380

- [ ]  Move JSON that is currently section 2B out of section 2.  Make it Section 4.
- [ ]  Add fixtures for the new section so the JSON is deployed automatically

**Comment by jgillis1** [comment]
@cjhskippy @TaraWilliamsPGH We have a build ticket for Section 4 but not a JSON/Fixtures ticket. Please confirm if putting this into Ice Cream Cake backlog is appropriate.

**Comment by TaraWilliamsPGH** [comment]
@cjhskippy @jgillis1 I honestly don't think it matters if we tag this one to I or J...the laundry list of I items is pretty long and I foresee J rollover. This is just a part of what has to get done before pen test. I do not believe it is blocking anything otherwise.

**Comment by cjhskippy** [comment]
@jgillis1 I agree with Tara!  This is moving content from section 2B.  I'd rather get 2B up and running in its current form before we move things around.

**Comment by jgillis1** [comment]
@mgwalker I believe you have completed this ticket, correct?

**Comment by mgwalker** [comment]
Yes, completed in #624.
