### ISSUE TITLE
Put CARTS behind a WAF

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#610]
In preparation for the pen test, the team asked which firewall solution is in use.  Either AWS WAF or Akamai would be viable, with a slight preference by the pen test team for Akamai.  At this time, the application is not behind a firewall.

AC:
- [x] Site used for pen testing (val environment) is behind a CMS-approved firewall
- [x] Production site is behind a CMS-approved firewall.

**Comment by jgillis1** [comment]
AWS WAF has been selected. 

From Doug: I implemented WAF yesterday. I restricted traffic to just geo location (only us and us territories). I then talked to Mannie who pointed me towards a WAF configuraiton that the cloud team created for MACPro Appian with some standard rules. I recreated what they did and that is applying to both our UI and API so those should be more “standard” WAF configurations based on the fact that CMS gave us that for MACPro.
