### ISSUE TITLE
Column Headings Display on the bottom of tables

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#638]
In Section 2, both of the tables have column headers that print underneath the table's contents.

In the screenshot below, you can see that the headings "Program", "Number of children enrolled...", etc. are below the data cells.  These headings should instead be the first row that appears in the table.

<img width="775" alt="Screen Shot 2020-09-23 at 2 13 44 PM" src="https://user-images.githubusercontent.com/1299543/94070576-4e1b5000-fda7-11ea-9d28-9b9ce8fb9e0c.png">

**Comment by jgillis1** [comment]
@TGriesemer I believe has a solution to this based on his original work on 2A. Let's see if that can be easily moved into the current code base.
