### ISSUE TITLE
FY19 + FY20 SEDS data for each state

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#639]
As a state user, I want to see my SEDS data so that I can easily know whether I need to answer additional questions based on percentage change of children enrolled.

[Section 2, Part 1](https://mdctcartsdev.cms.gov/sections/2020/02?dev=dev-ak) includes a table with enrollment data pulled from SEDS.  Update deployment scripts to include the following information for each state:
- Program name
- Number of children enrolled in FFY 2019
- Number of children enrolled in FFY 2020
- Percentage change year over year (should this be in the data or calculated?)

For the purposes of this story, we do not need to integrate with SEDS.  We can use the latest information available in SEDS and build it into the CARTS deployment scripts.  This means that if states submit new information in SEDS, it may be necessary to update this data and redeploy CARTS.  That is acceptable for MVP.

AC:
- [ ] Every state and territory has latest SEDS data included in the table.

Related to #193 (mapping SEDS data) and #189 (data migration plan)

**Comment by StephanieCoppel** [comment]
****need to discuss in sprint review - SEDS data CANNOT be hard coded in, integration is required for MVP****

**Comment by mblevins-collabralink** [comment]
@jgillis1 and I have had preliminary discussions on how to handle this, so she's prepared to discuss it.

**Comment by StephanieCoppel** [comment]
> @jgillis1 and I have had preliminary discussions on how to handle this, so she's prepared to discuss it.

fantastic, thank you!

**Comment by cjhskippy** [comment]
Closing - we're going to tackle the more-ambitious #640 to solve this issue instead.
