### ISSUE TITLE
Migrate Django API and MSSQL Container into repo

### ISSUE THREAD

**Issue by andrewadcock** [18F/cms-carts-seds#64]
A Django API and container for MSSQL have been built and need to be added to this project from the previous repository (https://github.cms.gov/macpro/cms-carts-seds). 

A Postgres container currently exists for use by Django but may need to be updated with additional setup commands.

**Comment by tadhg-ohiggins** [comment]
Will be unnecessary if #190 succeeds.

**Comment by TaraWilliamsPGH** [comment]
Closed because this work should be completed by Leidos by 8/15
