### ISSUE TITLE
Date range validation bug

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#642]
When entering a date range, if you accidentally put too many digits into the year column of the end date, it is not possible to correct the error. Attempts to delete a digit after validation has been applied are ignored.

Reproduction steps:
1. Go to https://mdctcartsdev.cms.gov/sections/2020/02?dev=dev-ak
2. Answer "yes" to part 2, question 3.
3. For question 3b start date, enter 02 / 2020
4. For question 3b end date, enter 02 / 20200 and hit tab to change focus to the next question
5. Navigate back to the year field of the end date.  Attempt to delete one of the characters.  It will remain unchanged.

**Comment by cjhskippy** [comment]
Seems relatively minor in impact - it's an unusual case, and it looks like it may correct itself after navigating to other form elements.

**Comment by mgwalker** [comment]
@alewoo28 also noticed that once a valid start and end date are entered, they can't be edited anymore. So... 😬

**Comment by jgillis1** [comment]
This is addressed in #508. Moving the example and closing out this duplicate ticket.
