### ISSUE TITLE
Profile information based on user role

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#656]
As a CHIP project officer, I want to see which states CARTS will allow me to manage in CARTS.

On the profile page, show the following information only to CHIP project officers (we can also show this info to DSCP users since they share the same user role):

AC:
- List of the POs "States Assigned"(Jenna has this)
- A list with each state associated with the PO user's account (Jenna to get this: EUA IDs are required)

**Comment by jgillis1** [comment]
[https://app.zenhub.com/files/226399669/34e4f9fd-1e90-405d-bea5-3b13b51ee1b4/download](https://app.zenhub.com/files/226399669/34e4f9fd-1e90-405d-bea5-3b13b51ee1b4/download)

**Comment by TaraWilliamsPGH** [comment]
Update from BOs - all POs should have no differentiation between them anymore. Assigning their view by the states they cover is not needed functionality in this application anymore.
