### ISSUE TITLE
3C Display Issues

### ISSUE THREAD

**Issue by jgillis1** [18F/cms-carts-seds#663]
- Part 2 Table: Denials for First-Time Applicants: Title and Hint are repeated

- Part 3, Question 4 is an un-editable text box followed by a Computed value. This should be editable.

- Part 3 Table: Enrollment Data for CHIP Redetermination: Title and Hint are repeated

- Part 3 Table: Disenrollment Data for CHIP Redetermination: Title is repeated

AC:

- [ ] Part 1, Table: Denials... Title and Hint shown only once

- [ ] Part 3, Question 4 is editable (integer)

- [ ] Part 3, Table: Enrollment... Title and Hint shown only once

- [ ] Part 3, Table: Disenrollment... Title shown only once

**Comment by mgwalker** [comment]
* Part 2, table: fixed in #777 
* Part 3, question 4: fixed, but I don't remember where
* Part 3, table: fixed in #777
* Part 3, table: fixed in #777
