### ISSUE TITLE
Duplicate table introduction

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#701]
The introductions to synthesized tables appears to be repeated in some places.  For example, in section 3c, the tables in question 5 repeat this text twice:

`Table: Redetermination in CHIP
These tables are auto-populated with the data you entered above.`

<img width="599" alt="Screen Shot 2020-09-29 at 10 49 02 AM" src="https://user-images.githubusercontent.com/1299543/94599239-05e7ac00-0245-11eb-8613-807d633f3952.png">

**Comment by StephanieCoppel** [comment]
Also section 3E, #10 "child" table

**Comment by erinzstrenio** [comment]
This is also happening in Section 5 for tables 1-7. Ideally just the first one (with hint text) in all cases would display.

<img width="519" alt="Screen Shot 2020-10-05 at 1 26 18 PM" src="https://user-images.githubusercontent.com/46569779/95117769-b99ddf80-070e-11eb-927b-5966cf4ab7e0.png">
