### ISSUE TITLE
Age range calculations: Do not allow totals to be inconsistent with individual age brackets

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#718]
In sections 3C and 3G, users are asked to provide two things:
- Data for children broken down by age groups (0-3, 4-6, etc.)
- Total data for children of all ages (0-16 in 3c; 0-18 in 3g)

Review of the current design leaves us worried that users will enter inconsistent data or be confused by the form structure.

In order to collect better data, reorganize questions in 3C and 3G to:
- [x] Add a question that verifies whether the state has data broken down by age groups (vs the total for all ages)
- [x] If the user answers yes, they do have data for individual age groups, show the form fields for each age group 
- [x] If the user answers no, they don't have data for age groups, only show an input field for the total
  - [x] Automatically calculate the totals based on the user's individual age group entries.

Related in 3C:
- [x] Update child questions (currently appearing as questions 3f, 4f, etc) to be same level as parent questions, and update question numbers/ids accordingly. 
- [x] Questions pertaining to `12 months later` and `18 months later` should be inactive for states to fill out next year

Content is updated to reflect these changes in the [template doc](https://docs.google.com/document/d/1pyCyUQPJKVEIKZ3cBTM8ZThxNeLiUzIKPPr0xfImtv4/edit?ts=5f6cea35#).

**Comment by mgwalker** [comment]
Making a note for myself: [here's an older commit](https://github.com/18F/cms-carts-seds/blob/612fd1d9435eb44763555562407f1e853fcb8d7d/docs/section-schemas/2020-ak-section-3.json#L941) showing how the checkbox was implemented, for reference.
