### ISSUE TITLE
Synthesized Tables with Unknown FMAP data should display "Not Available"

### ISSUE THREAD

**Issue by andrewadcock** [18F/cms-carts-seds#727]
As a user, if FMAP data is unknown in a synthesized table, data returned should display "Not Available". 

A/C
- [ ] In section 5, part 2, table 3, `FMAP` row: Data is displayed for FY2020, FY2021, and FY2022. If these values are unavailable, the cell should display "Not Available".
- [ ] In section 5, part 2, table 3, `Federal Share` row: Data is the product of several fields multiplied by FMAP data. If the FMAP data is unavailable the cell should display "Not Available".

**Comment by heymatthenry** [comment]
#734 Referenced above added the functionality to have cells with missing FMAP data display as "Not Available" and it *should* work for cells that perform computations on missing FMAP data too. Does that unblock you, @andrewadcock?
