### ISSUE TITLE
Copy Part 3 and Part 4 questions in Section 3C for Medicaid

### ISSUE THREAD

**Issue by erinzstrenio** [18F/cms-carts-seds#728]
- [x] Copy (what is currently) `Part 3: Redetermination in CHIP` to create a new `Part 4: Redetermination in Medicaid` (with same questions)
- [x] Update `Part 4: Redetermination in Medicaid` with references to Medicaid instead of CHIP @erinzstrenio 
- [x] Update (what is currently) `Part 4: Tracking a CHIP cohort over 18 months` to now be `Part 5: Tracking a CHIP cohort over 18 months`
- [x] Copy `Part 5: Tracking a CHIP cohort over 18 months` to create a new `Part 6: Tracking a Medicaid cohort over 18 month` (with same questions)
- [x] Update `Part 6: Redetermination in Medicaid` with references to Medicaid instead of CHIP @erinzstrenio

**Comment by mgwalker** [comment]
The last three there are covered in PR #726

**Comment by erinzstrenio** [comment]
The first two are now covered too!
