### ISSUE TITLE
fix alert on Section 3I

### ISSUE THREAD

**Issue by erinzstrenio** [18F/cms-carts-seds#764]
Alert under Section 3I, Part 2, question 2 should only display if users selected "no" for this question. 

<img width="723" alt="Screen Shot 2020-10-05 at 2 33 12 PM" src="https://user-images.githubusercontent.com/46569779/95123552-c2df7a00-0717-11eb-9e1a-c4d1d263d769.png">

**Comment by mgwalker** [comment]
This seems to be fixed? https://mdctcartsdev.cms.gov/sections/2020/03/i?dev=dev-ma

**Comment by erinzstrenio** [comment]
Hm, it's still showing up for me before the question is answered or if "yes" is selected. It should only appear if "no" is selected.

**Comment by mgwalker** [comment]
Weird! Alrighty then! Let's keep this here until we can confirm that it's fixed, then.

**Comment by StephanieCoppel** [comment]
it is not fixed for me either... lets keep this :)
