### ISSUE TITLE
Update 2B content/design to reflect feedback from legal 

### ISSUE THREAD

**Issue by erinzstrenio** [18F/cms-carts-seds#77]
A few minor content/design changes in 2B after going through the legal approval process. Updated in this doc! https://docs.google.com/document/d/1I-pnJCrsceEaIoFjHMQOqApQBBdyPj2e7Olqc0nK_eI/edit?usp=sharing

The main changes are: 

1) we're now giving users the first objective ("reduce the number of uninsured children") vs letting them pick their first objective, but they can still add additional objectives/goals to fit their state plans

2) all questions are now numbered

**Comment by cannandev** [comment]
Closing this and linking to the CL ticket to update.
