### ISSUE TITLE
section 3E edits - add part 1 and remove repeat question 

### ISSUE THREAD

**Issue by erinzstrenio** [18F/cms-carts-seds#773]
As a state user, I need to be able to answer "yes" or "no" if this section applies to me.

- [x] Add Part 1 question: "Does your state offer ESI/premium assistance"? 
- [x] Update current question ids to Part 2.
- [x] Remove repeat question 14 and update question ids that follow

**Comment by erinzstrenio** [comment]
PR #819

**Comment by erinzstrenio** [comment]
@timoballard @mgwalker Not sure who to ask about this but it section 3E, part 1 question 1 isn't showing up - any idea why this might be happening? I copied over the same JSON structure as section 3H but probably messed something up here. 

3E should follow the same logic as 3H — if states answer YES to part 1 question 1, they should see part 2. If they answer NO, then part 2 wouldn't apply to them and they don't need to see it (instead they should see a skip message).

**Comment by mgwalker** [comment]
Fixed the 3E, part 1 question 1 issue in PR #848!
