### ISSUE TITLE
Research spike: AREMAC endpoints

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-carts-seds#805]
We need to find out more about the AREMAC endpoint needs. E.g.:
- How will they connect?
- Do they have a preferred or required data format?
- How will we authenticate requests from AREMAC?
- etc.

Research ahead of #787

**Comment by TaraWilliamsPGH** [comment]
@tonydavydets - can you let me know if I have gathered enough intel to close this?

**Comment by tonydavydets** [comment]
@TaraWilliamsPGH  I believe so
