### ISSUE TITLE
Section 3C - Incorrect Title

### ISSUE THREAD

**Issue by StephanieCoppel** [18F/cms-carts-seds#814]
@erinzstrenio not sure if this is something you can update, if not please let me know and i will un-assign you. i thought this had been fixed previously, but i'm not sure if it was this specific section...

Section 3C should be titled "Eligibility, Enrollment and Operations" on both the left hand navigation bar and within the section itself. Currently it has the same title as Section 3B Substitution of Coverage. The content in the section is correct, just the title needs to be updated.

![bug.PNG](https://images.zenhubusercontent.com/5f2069da63dfc750bb46f86f/2245cc9a-5647-451b-9123-29c29cd99801)

**Comment by erinzstrenio** [comment]
Good catch! "Eligibility, Enrollment, and Operations" is the section 3 title, but 3C actually needs an updated title specific to the content in this section. I'll change it to "Renewal, Denials, and Retention."

**Comment by StephanieCoppel** [comment]
ah thank you @erinzstrenio !

**Comment by erinzstrenio** [comment]
PR #817
