### ISSUE TITLE
Status finite state machine

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/cms-carts-seds#836]
The official statuses:

+   In progress
+   Certified
+   Approved

There are also these implied/unofficial statuses:

+   Not started (before any state user for that state and year accesses a form, it isn't in progress, so some prior status is implied).
+   Submitted (Implied purely by the language in/around the app—there's no distinction between certifying and “submitting and certifying”).
+   Uncertified (without this, the form goes directly from **Certified** to **In progress**, but, similar to **Not started**, it can't be in progress until a state user does something with it, so this status is implied).
+   Published (eventually the report is made public and published to medicaid.gov).

This image is also relevant:
![image.png](https://images.zenhubusercontent.com/5f2069da63dfc750bb46f86f/81578f82-3522-479c-9882-df202632dfd0)

As is this mural: https://app.mural.co/t/upmc4555/m/upmc4555/1601924190266/917889a4d9489374a4f5fd0a043f9ed41f27bb8c

From the above, it looks to me that the status flow is as follows:
![image](https://user-images.githubusercontent.com/2626258/96220118-feaae880-0f3c-11eb-9c94-e8c09f7c3afb.png)

**Submitted** is probably unnecessary; I include it above purely because of existing content that suggests it exists in some meaningful way.

The above shows what statuses lead to other statuses, and which user roles can make which status changes.

The status also determines whether or not editing is possible—editing is possible only when the state user could change the status, that is, when the status is **Not started**, **In progress**, or **Uncertified**.

The issue or issues arising from this involve:

+   Tying whether or not editing is possible to the current status of the form (frontend).
+   Tying whether or not editing is possible to the current status of the form (backend).
+    Displaying status—and whether or not the form contents are editable—to users.
+   The UI for whether a user can change the status and how to do so if they can (including any confirmation steps).
+   The backend enforcing the status change rules as shown in the above flowchart.

**Comment by StephanieCoppel** [comment]
Morning, thanks for putting this all in a ticket! I've updated the roles chart in the ticket above, and reviewed your notes which all appear accurate to me. Are there any points of confusion remaining here that I can clarify? If so please ask here and tag me, thanks!

**Comment by StephanieCoppel** [comment]
responding to 'remaining issues':

- Tying whether or not editing is possible to the current status of the form (frontend). - created story 841

- Tying whether or not editing is possible to the current status of the form (backend). - created story 842

- Displaying status—and whether or not the form contents are editable—to users. - i think the status is shown at the top of the form and is a story just completed in this sprint. and the editable piece is captured in the above stories, frontend and backend. if this doesn't capture everything let me know what holes you see.

- The UI for whether a user can change the status and how to do so if they can (including any confirmation steps). - so i think a user can already do this - certify and submit is built out, we have stories to build out the accept or uncertify statuses, does something more need to be created for this?

- The backend enforcing the status change rules as shown in the above flowchart. - we have stories capturing each piece of the workflow.... does this not cover everything?

**Comment by tadhg-ohiggins** [comment]
@StephanieCoppel In the above, there's no way to go from `published` to anything else. But we know that updates sometimes occur post-publication. I don't know who's responsible for making changes possible again at that point, should we assume that either CHIP PO or Business officer users can change the status back to `uncertified`? Should we also make it possible to go from `approved` to `uncertified`, since that also seems likely to happen?

**Comment by StephanieCoppel** [comment]
@tadhg-ohiggins that's a great point, yes there should be an option for the CHIP project officer (and business owner since they now have the same permissions) to uncertify an approved form. i'm not sure that's quite as frequent as going from certified to uncertified but still a good failsafe either way (in the current process there's essentially just certified and uncertified, the approved stage is new)

**Comment by tadhg-ohiggins** [comment]
@StephanieCoppel adding those paths and merging both business owner and project officer roles into `CO User` creates this flow, does it seem correct to you?
![image](https://user-images.githubusercontent.com/2626258/96480104-a7cc3a00-11ee-11eb-818c-a63917c60263.png)

**Comment by StephanieCoppel** [comment]
@tadhg-ohiggins  yes these look correct. the only thing and this may be so small its negligible, is that on the CO user flow, the flow can just stop at 'published' - like uncertified at that point is an option but it is also content to just stay in published. i think that's implied in the flow but just wanted to state it anyway
