### ISSUE TITLE
update copy on Certify and Submit page

### ISSUE THREAD

**Issue by erinzstrenio** [18F/cms-carts-seds#844]
Update the copy to match what's in this [google doc](https://docs.google.com/document/d/1cCUtj1fiHd9HxNVknyHwKLiorT428NQ5G5AMLMDr8qA/edit#heading=h.484v62e5iw7d).

(Note: there's currently a typo: `reviewd`)

![Screen Shot 2020-10-16 at 13 54 17](https://user-images.githubusercontent.com/46569779/96309132-53e10b80-0fca-11eb-9cfe-24a9fb4a16c7.png)

**Comment by TaraWilliamsPGH** [comment]
@StephanieCoppel - Erin updated the copy...do we need to add a new story for making these changes to certify and submit page?
