### ISSUE TITLE
update copy in Section 4 for new sample objectives

### ISSUE THREAD

**Issue by erinzstrenio** [18F/cms-carts-seds#845]
- [x] update intro about editing sample objectives
- [x] hint text needs updating on the new sample objectives
- [x] remove period in first objective 
- [x] update verb tenses to be consistent for all objectives

**Comment by StephanieCoppel** [comment]
@erinzstrenio - is this something we can pull into the current sprint? if not then we'll put it in next sprint, but if it can be done this sprint that would be awesome!

**Comment by erinzstrenio** [comment]
yes! I can make these updates for this sprint. just tagged for King Cake.

**Comment by StephanieCoppel** [comment]
@erinzstrenio  YOU ARE AWESOME

**Comment by erinzstrenio** [comment]
PR #857

**Comment by mgwalker** [comment]
Closed by #857
