### ISSUE TITLE
Prototype Section 1

### ISSUE THREAD

**Issue by cannandev** [18F/cms-carts-seds#90]
- [x] new Input Range component
- [x] Hide Section Part if it does not apply based on the programType for the State (i.e. mCHIP programType has sCHIP Parts 1 & 3 hidden. sCHIP programType has mCHIP Parts 2 & 3 hidden. comboCHIP has no Parts hidden.)
- [x] Keep note to skip Part visible if Part is hidden
- [x] Parts 1 & 2, Questions 3 & 4: Show hint or Skip to Question 5 if they are inactive
- [x] For Input Range component, do not allow end value to be less than start value

~~**Versions for testing:**~~
~~- [ ] Oatmeal Raisin~~
~~- [ ] Snickerdoodle~~
~~- [ ] Chocolate Chip~~

[Section 1 Content link](https://docs.google.com/document/d/1P6mFgRd8dsm1YIiHo1pDcIzWA119k5tIKNGTbbC9WVQ/edit)
Please copy and paste content to avoid grammatical errors. 

![idea for nested ranges](https://user-images.githubusercontent.com/381122/85067206-4d5a9880-b17e-11ea-8f5a-f7c09e846736.png)

**Comment by cannandev** [comment]
Updated issue with new content gdoc link.

**Comment by jgillis1** [comment]
@erinzstrenio  added some questions for you to the CARTS Section 1 gdoc.

**Comment by cannandev** [comment]
@jgillis1 So we've decided to go with the conditional question/answer version for the next round of user testing. Please continue building as outlined in the [Section 1 document](https://docs.google.com/document/d/1P6mFgRd8dsm1YIiHo1pDcIzWA119k5tIKNGTbbC9WVQ/edit?ts=5ee11c5a#heading=h.qf3ce0ndkqb1). 

If the users give feedback indicating they preferred the old table version, we'll update code using a flexbox grid, not an HTML table.

**Comment by erinzstrenio** [comment]
<img width="562" alt="Screen Shot 2020-07-01 at 1 11 53 PM" src="https://user-images.githubusercontent.com/46569779/86277873-11bbc780-bb9d-11ea-8498-73908b5114d0.png">

If they input an incorrect range (ie 50 to 10 in this example) would they get an error message here or upon submitting?
