### ISSUE TITLE
Prototype Section 2A

### ISSUE THREAD

**Issue by cannandev** [18F/cms-carts-seds#93]
CMS Table component - https://design.cms.gov/components/table/
Section 2A content doc - https://docs.google.com/document/d/1_sZeyUepMveNvS0z_jru-8hzSy5XpZLcd-ODLA7MjAc/edit
Please copy and paste text to avoid grammatical errors.

**Comment by cannandev** [comment]
For demo purposes, please add static data to table. 

We're looking into how this info is currently captured/updated.

**Comment by jgillis1** [comment]
@cannandev @erinzstrenio Could you confirm that Section 2A should have the FY2019 answers tab? If so, should it contain all the tables as they would have looked for 2019 or just the responses to the questions they would have needed to respond to?

**Comment by erinzstrenio** [comment]
@jgillis1 We actually don't want to have this feature in 2A! Thanks for raising the question, @jgillis1. Would it be helpful if we noted in the content docs which sections should have the last year's answers feature and which shouldn't (or should we capture that info somewhere else)?

**Comment by jgillis1** [comment]
@erinzstrenio A note in the content doc would be perfect. Thank you Erin!

**Comment by erinzstrenio** [comment]
Cool. I'll go back and add it to our current docs and start including it for future sections!

**Comment by jgillis1** [comment]
Thank you!
